spring:
  application:
    name: supplier
  jackson:
    serialization:
      write-dates-as-timestamps: false   # serialize LocalDateTime as ISO-8601 string
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      client-id: supplier-client
